# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OLS_Rcpp <- function(X, y) {
    .Call(`_MyRcppPackage_OLS_Rcpp`, X, y)
}

rcpp_hello_world <- function() {
    .Call(`_MyRcppPackage_rcpp_hello_world`)
}

